/**
 * Data Loader Utilities
 * Loads sample data for Phases 1-6 (JSON-based prototyping)
 * Will be replaced with API calls in Phase 7
 */

import type { Student } from '../types';

/**
 * Sample students data
 * 10 diverse student records with various skill levels, batches, and coaches
 */
export const STUDENTS_DATA: Student[] = [
  {
    id: 'student-001',
    fullName: 'Arjun Verma',
    dateOfBirth: new Date('2012-05-15'),
    age: 13,
    gender: 'Male',
    contactPhone: '9876543210',
    email: 'arjun.v@email.com',
    guardianName: 'Rajesh Verma',
    guardianPhone: '9876543200',
    baidNumber: 'BAID-2026-001',
    batchId: 'batch-001',
    assignedCoachId: 'user-002',
    profilePhoto: undefined,
    height: 155,
    weight: 48,
    bmi: 20.0,
    bloodGroup: 'O+',
    medicalConditions: undefined,
    emergencyContact: '9876543200',
    strengths: ['Quick footwork', 'Backhand shot'],
    weaknesses: ['Service consistency'],
    coachFeedback: 'Good fundamentals, needs work on service technique.',
    skillLevel: 'Beginner',
    createdAt: new Date('2026-01-05T09:00:00Z'),
    updatedAt: new Date('2026-01-15T10:30:00Z'),
  },
  {
    id: 'student-002',
    fullName: 'Neha Sharma',
    dateOfBirth: new Date('2010-08-22'),
    age: 15,
    gender: 'Female',
    contactPhone: '9876543211',
    email: 'neha.s@email.com',
    guardianName: 'Priya Sharma',
    guardianPhone: '9876543201',
    baidNumber: 'BAID-2026-002',
    batchId: 'batch-001',
    assignedCoachId: 'user-002',
    profilePhoto: undefined,
    height: 162,
    weight: 55,
    bmi: 20.9,
    bloodGroup: 'B+',
    medicalConditions: undefined,
    emergencyContact: '9876543201',
    strengths: ['Court positioning', 'Drop shots'],
    weaknesses: ['Power in smash'],
    coachFeedback: 'Excellent court sense. Focus on building power in overhead shots.',
    skillLevel: 'Intermediate',
    createdAt: new Date('2026-01-06T09:00:00Z'),
    updatedAt: new Date('2026-01-14T14:00:00Z'),
  },
  {
    id: 'student-003',
    fullName: 'Rohan Kapoor',
    dateOfBirth: new Date('2008-03-10'),
    age: 17,
    gender: 'Male',
    contactPhone: '9876543212',
    email: 'rohan.k@email.com',
    guardianName: undefined,
    guardianPhone: undefined,
    baidNumber: 'BAID-2026-003',
    batchId: 'batch-002',
    assignedCoachId: 'user-003',
    profilePhoto: undefined,
    height: 175,
    weight: 68,
    bmi: 22.2,
    bloodGroup: 'A+',
    medicalConditions: undefined,
    emergencyContact: '9876543212',
    strengths: ['Rally play', 'Stamina', 'Attacking shots'],
    weaknesses: ['Defensive positioning'],
    coachFeedback: 'Strong attacker. Needs to develop defensive strategies for competitive matches.',
    skillLevel: 'Advanced',
    createdAt: new Date('2026-01-07T09:00:00Z'),
    updatedAt: new Date('2026-01-13T11:45:00Z'),
  },
  {
    id: 'student-004',
    fullName: 'Ananya Singh',
    dateOfBirth: new Date('2011-11-28'),
    age: 14,
    gender: 'Female',
    contactPhone: '9876543213',
    email: 'ananya.s@email.com',
    guardianName: 'Vikram Singh',
    guardianPhone: '9876543202',
    baidNumber: 'BAID-2026-004',
    batchId: 'batch-001',
    assignedCoachId: 'user-002',
    profilePhoto: undefined,
    height: 160,
    weight: 52,
    bmi: 20.3,
    bloodGroup: 'AB+',
    medicalConditions: 'Mild asthma',
    emergencyContact: '9876543202',
    strengths: ['Agility', 'Net shots'],
    weaknesses: ['Endurance', 'Power'],
    coachFeedback: 'Quick and nimble. Work on building stamina for longer rallies.',
    skillLevel: 'Intermediate',
    createdAt: new Date('2026-01-08T09:00:00Z'),
    updatedAt: new Date('2026-01-12T15:20:00Z'),
  },
  {
    id: 'student-005',
    fullName: 'Karan Desai',
    dateOfBirth: new Date('2007-06-05'),
    age: 18,
    gender: 'Male',
    contactPhone: '9876543214',
    email: 'karan.d@email.com',
    guardianName: undefined,
    guardianPhone: undefined,
    baidNumber: 'BAID-2026-005',
    batchId: 'batch-003',
    assignedCoachId: 'user-003',
    profilePhoto: undefined,
    height: 178,
    weight: 72,
    bmi: 22.7,
    bloodGroup: 'O-',
    medicalConditions: undefined,
    emergencyContact: '9876543214',
    strengths: ['All-around skills', 'Mental game', 'Doubles coordination'],
    weaknesses: [],
    coachFeedback: 'Well-rounded player. Ready for competitive tournaments. Focus on consistency.',
    skillLevel: 'Professional',
    createdAt: new Date('2026-01-09T09:00:00Z'),
    updatedAt: new Date('2026-01-15T09:00:00Z'),
  },
  {
    id: 'student-006',
    fullName: 'Simran Malhotra',
    dateOfBirth: new Date('2013-02-14'),
    age: 12,
    gender: 'Female',
    contactPhone: '9876543215',
    email: 'simran.m@email.com',
    guardianName: 'Anjali Malhotra',
    guardianPhone: '9876543203',
    baidNumber: undefined,
    batchId: 'batch-002',
    assignedCoachId: 'user-003',
    profilePhoto: undefined,
    height: 148,
    weight: 42,
    bmi: 19.2,
    bloodGroup: 'B-',
    medicalConditions: undefined,
    emergencyContact: '9876543203',
    strengths: ['Enthusiasm', 'Learning ability'],
    weaknesses: ['Technique consistency', 'Court awareness'],
    coachFeedback: 'Very eager learner. Needs foundational technique work before advanced drills.',
    skillLevel: 'Beginner',
    createdAt: new Date('2026-01-10T09:00:00Z'),
    updatedAt: new Date('2026-01-14T12:30:00Z'),
  },
  {
    id: 'student-007',
    fullName: 'Aditya Rao',
    dateOfBirth: new Date('2009-09-19'),
    age: 16,
    gender: 'Male',
    contactPhone: '9876543216',
    email: 'aditya.r@email.com',
    guardianName: 'Suresh Rao',
    guardianPhone: '9876543204',
    baidNumber: 'BAID-2026-006',
    batchId: 'batch-003',
    assignedCoachId: 'user-003',
    profilePhoto: undefined,
    height: 172,
    weight: 65,
    bmi: 21.9,
    bloodGroup: 'O+',
    medicalConditions: undefined,
    emergencyContact: '9876543204',
    strengths: ['Consistency', 'Forehand drive'],
    weaknesses: ['Backhand flexibility'],
    coachFeedback: 'Developing player with good consistency. Work on backhand versatility.',
    skillLevel: 'Intermediate',
    createdAt: new Date('2026-01-11T09:00:00Z'),
    updatedAt: new Date('2026-01-13T16:00:00Z'),
  },
  {
    id: 'student-008',
    fullName: 'Priya Nambiar',
    dateOfBirth: new Date('2008-12-03'),
    age: 17,
    gender: 'Female',
    contactPhone: '9876543217',
    email: 'priya.n@email.com',
    guardianName: undefined,
    guardianPhone: undefined,
    baidNumber: 'BAID-2026-007',
    batchId: 'batch-002',
    assignedCoachId: 'user-003',
    profilePhoto: undefined,
    height: 168,
    weight: 60,
    bmi: 21.3,
    bloodGroup: 'A-',
    medicalConditions: undefined,
    emergencyContact: '9876543217',
    strengths: ['Strategic thinking', 'Movement patterns'],
    weaknesses: ['Aggressive play'],
    coachFeedback: 'Smart defensive player. Encourage more attacking opportunities in training.',
    skillLevel: 'Advanced',
    createdAt: new Date('2026-01-12T09:00:00Z'),
    updatedAt: new Date('2026-01-15T13:20:00Z'),
  },
  {
    id: 'student-009',
    fullName: 'Vikram Joshi',
    dateOfBirth: new Date('2014-04-07'),
    age: 11,
    gender: 'Male',
    contactPhone: '9876543218',
    email: 'vikram.j@email.com',
    guardianName: 'Ramesh Joshi',
    guardianPhone: '9876543205',
    baidNumber: undefined,
    batchId: 'batch-001',
    assignedCoachId: 'user-002',
    profilePhoto: undefined,
    height: 145,
    weight: 40,
    bmi: 19.0,
    bloodGroup: 'B+',
    medicalConditions: undefined,
    emergencyContact: '9876543205',
    strengths: ['Speed'],
    weaknesses: ['Shot accuracy', 'Power development'],
    coachFeedback: 'Young and energetic. Focus on basic technique before advanced movements.',
    skillLevel: 'Beginner',
    createdAt: new Date('2026-01-13T09:00:00Z'),
    updatedAt: new Date('2026-01-14T10:15:00Z'),
  },
  {
    id: 'student-010',
    fullName: 'Sapna Reddy',
    dateOfBirth: new Date('2009-07-30'),
    age: 16,
    gender: 'Female',
    contactPhone: '9876543219',
    email: 'sapna.r@email.com',
    guardianName: 'Suman Reddy',
    guardianPhone: '9876543206',
    baidNumber: 'BAID-2026-008',
    batchId: 'batch-003',
    assignedCoachId: 'user-003',
    profilePhoto: undefined,
    height: 165,
    weight: 58,
    bmi: 21.3,
    bloodGroup: 'O+',
    medicalConditions: undefined,
    emergencyContact: '9876543206',
    strengths: ['Control', 'Precision shots'],
    weaknesses: ['Baseline clearing'],
    coachFeedback: 'Excellent shot selection and precision. Needs to work on power and baseline play.',
    skillLevel: 'Advanced',
    createdAt: new Date('2026-01-14T09:00:00Z'),
    updatedAt: new Date('2026-01-15T14:40:00Z'),
  },
];

/**
 * Load students data
 * Returns all sample students
 */
export const loadStudents = (): Student[] => {
  return STUDENTS_DATA;
};

/**
 * Load a single student by ID
 */
export const loadStudent = (id: string): Student | undefined => {
  return STUDENTS_DATA.find((s) => s.id === id);
};

/**
 * Get students filtered by batch
 */
export const loadStudentsByBatch = (batchId: string): Student[] => {
  return STUDENTS_DATA.filter((s) => s.batchId === batchId);
};

/**
 * Get students assigned to a coach
 */
export const loadStudentsByCoach = (coachId: string): Student[] => {
  return STUDENTS_DATA.filter((s) => s.assignedCoachId === coachId);
};
